# Pandas Student Workbook

Questions only. Write answers in the empty code cells below each question.

Q1. Import pandas as pd.

In [1]:
import pandas as pd

Q2. Create a Series containing 10, 20, 30, 40, 50.

In [2]:
s=pd.Series([10,20,30,40,50])

Q3. Create a Series with values [100, 200, 300] and index ['A', 'B', 'C'].

In [3]:
sp=pd.Series([100,200,300],index=['A','B','C'])
sp

A    100
B    200
C    300
dtype: int64

Q4. Access the value with label 'B' from a Series.

In [4]:
print(sp['B'])

200

Q5. Create a Series and display values greater than 25.

In [5]:
print(s[s>25])

2    30
3    40
4    50
dtype: int64

Q6. Find the sum(), mean() and max() of a Series.

In [6]:
print(sp.mean())
print(sp.sum())
print(sp.max())

200.0
600
300

Q7. Create a DataFrame from a dictionary containing Name and Score columns.

In [7]:
data= pd.DataFrame({'Name':['Sourav','Richa','Mridul'],
'Score':[85,90,95],'city':[None,'Assam','Delhi'],'Price':[100,200,300],'quantity':[1,2,3]})

Q8. Create a DataFrame with 5 students and 3 columns.

In [8]:
students=pd.DataFrame({'Name':['alia','salman','sourav','richa','mridul'],'score':[80,85,75,90,98],'rollno':[1,2,3,4,5]})

Q9. Display the first 3 rows using head().

In [9]:
students.head(3)

     Name  score  rollno
0    alia     80       1
1  salman     85       2
2  sourav     75       3

Q10. Display the last 2 rows using tail().

In [10]:
students.tail(3)

     Name  score  rollno
2  sourav     75       3
3   richa     90       4
4  mridul     98       5

Q11. Find the shape of a DataFrame.

In [11]:
students.shape

(5, 3)

Q12. Display column names using columns.

In [12]:
students.columns

Index(['Name', 'score', 'rollno'], dtype='str')

Q13. Check data types using dtypes.

In [13]:
students.dtypes

Name        str
score     int64
rollno    int64
dtype: object

Q14. Use info() on a DataFrame.

In [14]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   score   5 non-null      int64
 2   rollno  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

Q15. Use describe() on a DataFrame.

In [15]:
students.describe()

           score    rollno
count   5.000000  5.000000
mean   85.600000  3.000000
std     8.905055  1.581139
min    75.000000  1.000000
25%    80.000000  2.000000
50%    85.000000  3.000000
75%    90.000000  4.000000
max    98.000000  5.000000

Q16. Select a single column from a DataFrame.

In [16]:
students.columns[1]

'score'

Q17. Select multiple columns from a DataFrame.

In [17]:
students.columns[1:3]

Index(['score', 'rollno'], dtype='str')

Q18. Use loc to access a specific row and column.

In [18]:
students.loc[1,'Name']

'salman'

Q19. Use iloc to access the first row and second column.

In [19]:
students.iloc[1,0]

'salman'

Q20. Filter rows where Score > 80.

In [20]:
students[students['score']>80]

     Name  score  rollno
1  salman     85       2
3   richa     90       4
4  mridul     98       5

Q21. Filter rows where City = 'Delhi'.

In [21]:
data[data['city']=='Delhi']

     Name  Score   city  Price  quantity
2  Mridul     95  Delhi    300         3

Q22. Apply multiple conditions using & and |.

In [22]:
data[(data['Score']>80)&(data['city']=='Delhi')]
data[(data['Score']>80)|(data['city']=='Assam')]

     Name  Score   city  Price  quantity
0  Sourav     85    NaN    100         1
1   Richa     90  Assam    200         2
2  Mridul     95  Delhi    300         3

Q23. Find missing values using isnull().

In [23]:
data.isnull()

    Name  Score   city  Price  quantity
0  False  False   True  False     False
1  False  False  False  False     False
2  False  False  False  False     False

Q24. Count missing values in each column.

In [24]:
data.isnull().sum()

Name        0
Score       0
city        1
Price       0
quantity    0
dtype: int64

Q25. Fill missing values with a fixed value using fillna().

In [25]:
data.fillna('Moga')

     Name  Score   city  Price  quantity
0  Sourav     85   Moga    100         1
1   Richa     90  Assam    200         2
2  Mridul     95  Delhi    300         3

Q26. Drop rows containing missing values using dropna().

In [26]:
data.dropna()

     Name  Score   city  Price  quantity
1   Richa     90  Assam    200         2
2  Mridul     95  Delhi    300         3

Q27. Create a new column Total = Price * Quantity.

In [27]:
data["total"]=data["Price"]*data["quantity"]
data

     Name  Score   city  Price  quantity  total
0  Sourav     85    NaN    100         1    100
1   Richa     90  Assam    200         2    400
2  Mridul     95  Delhi    300         3    900

Q28. Rename a column using rename().

In [28]:
data.rename(columns={'total':'Total_Price'},inplace=True)

Q29. Convert a column datatype using astype().

In [29]:
data.astype({'Total_Price':"float"})

     Name  Score   city  Price  quantity  Total_Price
0  Sourav     85    NaN    100         1        100.0
1   Richa     90  Assam    200         2        400.0
2  Mridul     95  Delhi    300         3        900.0

Q30. Remove a column using drop().

In [30]:
data.drop('Score',axis=1)

     Name   city  Price  quantity  Total_Price
0  Sourav    NaN    100         1          100
1   Richa  Assam    200         2          400
2  Mridul  Delhi    300         3          900

Q31. Find frequency counts using value_counts().

In [31]:
data['city'].value_counts()

city
Assam    1
Delhi    1
Name: count, dtype: int64

Q32. Sort a DataFrame by Score in descending order.

In [32]:
data.sort_values(by="Score",ascending=False)

     Name  Score   city  Price  quantity  Total_Price
2  Mridul     95  Delhi    300         3          900
1   Richa     90  Assam    200         2          400
0  Sourav     85    NaN    100         1          100

Q33. Group data by City and find average Score.

In [33]:
data.groupby("city")["Score"].mean()

city
Assam    90.0
Delhi    95.0
Name: Score, dtype: float64

Q34. Group data by Department and calculate total Salary.

In [34]:
data["dept"]=["IT","cse","IT"]
data["salary"]=[32000,48000,45000]
data.groupby("dept")["salary"].sum()

dept
IT     77000
cse    48000
Name: salary, dtype: int64

Q35. Perform multiple aggregations using agg().

In [35]:
data.groupby('dept').agg({'salary': ['sum', 'mean', 'max']})

     salary
        sum     mean    max
dept
IT    77000  38500.0  45000
cse   48000  48000.0  48000

Q36. Merge two DataFrames using a common key.

In [36]:
df1 = pd.DataFrame({'key': ['A', 'B', 'C', 'D'], 'value': [1, 2, 3, 4]})
df2 = pd.DataFrame({'key': ['B', 'D', 'E', 'F'], 'value2': [5, 6, 7, 8]})
merged_df = pd.merge(df1, df2, on='key')
display(merged_df)

  key  value  value2
0   B      2       5
1   D      4       6

Q37. Perform a left join between two DataFrames.

In [37]:
left_join_df = pd.merge(df1, df2, on='key', how='left')
display(left_join_df)

  key  value  value2
0   A      1     NaN
1   B      2     5.0
2   C      3     NaN
3   D      4     6.0

Q38. Concatenate two DataFrames row-wise.

In [38]:
df_concat_rows = pd.concat([df1, df2])
display(df_concat_rows)

  key  value  value2
0   A    1.0     NaN
1   B    2.0     NaN
2   C    3.0     NaN
3   D    4.0     NaN
0   B    NaN     5.0
1   D    NaN     6.0
2   E    NaN     7.0
3   F    NaN     8.0

Q39. Concatenate two DataFrames column-wise.

In [39]:
df_concat_cols = pd.concat([df1, df2], axis=1)
display(df_concat_cols)

  key  value key  value2
0   A      1   B       5
1   B      2   D       6
2   C      3   E       7
3   D      4   F       8

Q40. Mini Project: Create a sales DataFrame and answer business questions using filtering, groupby, and aggregation.

## Q40. Mini Project: Create a sales DataFrame and answer business questions using filtering, groupby, and aggregation.

In [40]:
sales_data = {
    'Date': pd.to_datetime(['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03', '2023-01-03']),
    'Region': ['East', 'West', 'East', 'West', 'East', 'West'],
    'Product': ['A', 'B', 'A', 'C', 'B', 'A'],
    'Units_Sold': [10, 15, 12, 8, 20, 5],
    'Price_Per_Unit': [2.5, 3.0, 2.5, 4.0, 3.0, 2.5]
}
sales_df = pd.DataFrame(sales_data)
sales_df['Total_Sales'] = sales_df['Units_Sold'] * sales_df['Price_Per_Unit']
display(sales_df)

        Date Region Product  Units_Sold  Price_Per_Unit  Total_Sales
0 2023-01-01   East       A          10             2.5         25.0
1 2023-01-01   West       B          15             3.0         45.0
2 2023-01-02   East       A          12             2.5         30.0
3 2023-01-02   West       C           8             4.0         32.0
4 2023-01-03   East       B          20             3.0         60.0
5 2023-01-03   West       A           5             2.5         12.5

### Business Question 1: What are the total sales per region?

In [41]:
total_sales_by_region = sales_df.groupby('Region')['Total_Sales'].sum().reset_index()
display(total_sales_by_region)

  Region  Total_Sales
0   East        115.0
1   West         89.5

### Business Question 2: Which product had the highest units sold on '2023-01-01'?

In [42]:
sales_on_jan_1 = sales_df[sales_df['Date'] == '2023-01-01']
highest_units_jan_1 = sales_on_jan_1.loc[sales_on_jan_1['Units_Sold'].idxmax()]
display(highest_units_jan_1)

Date              2023-01-01 00:00:00
Region                           West
Product                             B
Units_Sold                         15
Price_Per_Unit                    3.0
Total_Sales                      45.0
Name: 1, dtype: object

### Business Question 3: What is the average price per unit for each product?

In [43]:
avg_price_per_product = sales_df.groupby('Product')['Price_Per_Unit'].mean().reset_index()
display(avg_price_per_product)

  Product  Price_Per_Unit
0       A             2.5
1       B             3.0
2       C             4.0